serverAddr = "114.215.175.120"
serverPort = 7000

[auth]
token = "123456"

# 用 TCP 方式穿透 portainer（最稳、不报错）
[[proxies]]
name = "portainer-tcp"
type = "tcp"
localIP = "portainer"
localPort = 9000
remotePort = 9000

[[proxies]]
name = "vaultwarden-tcp"
type = "tcp"
localIP = "host.docker.internal"
localPort = 8081
remotePort = 8081

[[proxies]]
name = "sql-optimizer-api"
type = "tcp"
localIP = "sql-optimizer"
localPort = 8001
remotePort = 18000

[[proxies]]
name = "portainer-edge"
type = "tcp"
localIP = "portainer"
localPort = 8000
remotePort = 8000
